/* eslint-disable no-undef */

const CopyWebpackPlugin = require("copy-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const webpack = require("webpack");
const Dotenv = require("dotenv-webpack");
const path = require("path");
const fs = require("fs");
const os = require("os");

const urlDev = "https://localhost:5173/";
const urlProd = "https://www.contoso.com/"; // CHANGE THIS TO YOUR PRODUCTION DEPLOYMENT LOCATION

// Reads the dev certs generated by `office-addin-dev-certs` directly instead
// of calling its getHttpsServerOptions(), which also tries to install the CA
// into the system trust store (needs an interactive sudo prompt on Linux).
// We don't need that here: the dev server is exposed to other machines via
// a cloudflared tunnel, which presents its own publicly-trusted certificate.
function getHttpsOptions() {
  const certDir = path.join(os.homedir(), ".office-addin-dev-certs");
  return {
    ca: fs.readFileSync(path.join(certDir, "ca.crt")),
    cert: fs.readFileSync(path.join(certDir, "localhost.crt")),
    key: fs.readFileSync(path.join(certDir, "localhost.key")),
  };
}

module.exports = async (env, options) => {
  const dev = options.mode === "development";
  const config = {
    devtool: "source-map",
    experiments: {
      asyncWebAssembly: true,
    },
    context: path.resolve(__dirname, "./"),
    entry: {
      polyfill: ["core-js/stable", "regenerator-runtime/runtime"],
      react: ["react", "react-dom"],
      taskpane: {
        import: ["./src/taskpane/index.tsx", "./src/taskpane/taskpane.html"],
        dependOn: "react",
      },
      commands: "./src/commands/commands.ts",
    },
    output: {
      filename: "[name].[contenthash].js",
      clean: true,
    },
    resolve: {
      extensions: [".ts", ".tsx", ".html", ".js"],
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
          },
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: ["ts-loader"],
        },
        {
          test: /\.html$/,
          exclude: /node_modules/,
          use: "html-loader",
        },
        {
          test: /\.(png|jpg|jpeg|ttf|woff|woff2|gif|ico)$/,
          type: "asset/resource",
          generator: {
            filename: "assets/[name][ext][query]",
          },
        },
      ],
    },
    plugins: [
      new Dotenv(),
      new HtmlWebpackPlugin({
        filename: "taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["polyfill", "taskpane", "react"],
      }),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: "assets/*",
            to: "assets/[name][ext][query]",
          },
          {
            from: "assets/model",
            to: "assets/model",
          },
          {
            from: "manifest*.xml",
            to: "[name]" + "[ext]",
            transform(content) {
              if (dev) {
                return content;
              } else {
                return content.toString().replace(new RegExp(urlDev, "g"), urlProd);
              }
            },
          },
        ],
      }),
      new HtmlWebpackPlugin({
        filename: "commands.html",
        template: "./src/commands/commands.html",
        chunks: ["polyfill", "commands"],
      }),
      new HtmlWebpackPlugin({
        filename: "auth-fallback.html",
        template: "./src/auth/auth-fallback.html",
        chunks: ["polyfill"],
      }),
      new webpack.ProvidePlugin({
        Promise: ["es6-promise", "Promise"],
      }),
    ],
    devServer: {
      host: "0.0.0.0",
      hot: false,
      liveReload: false,
      client: false,
      // Proxy only in development mode (options.mode === 'development')
      ...(options.mode === "development"
        ? {
            proxy: [
              {
                context: "/api",
                target: process.env.DEV_API_TARGET || "http://localhost:3003", // backend dev (plain HTTP in dev)
                secure: false, // aceita certificado auto‑assinado
                changeOrigin: true,
              },
            ],
          }
        : {}),
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Permissions-Policy": "clipboard-write=*",
      },
      allowedHosts: "all",
      server: {
        type: "https",
        options:
          env.WEBPACK_BUILD || options.https !== undefined
            ? options.https
            : await getHttpsOptions(),
      },
      port: process.env.npm_package_config_dev_server_port || 5173,
    },
  };

  return config;
};
