/* eslint-disable no-undef */

const CopyWebpackPlugin = require("copy-webpack-plugin");
const HtmlWebpackPlugin = require("html-webpack-plugin");
const webpack = require("webpack");
const Dotenv = require("dotenv-webpack");
const path = require("path");
const fs = require("fs");
const os = require("os");

const devHost = "localhost:5173";
// M5: domínio oficial de produção, definido via env — nunca hardcoded aqui.
// Só é exigido (e só quebra o build) quando o build é de fato de produção;
// dev e o build do túnel não dependem dessa variável.
const urlProd = process.env.PROD_APP_DOMAIN
  ? `${process.env.PROD_APP_DOMAIN.replace(/\/$/, "")}/`
  : undefined;
// M5: o manifesto referencia o host de dev em três formatos diferentes —
// "https://localhost:5173/" (com barra), "https://localhost:5173"
// (AppDomain, sem barra) e "api://localhost:5173/..." (WebApplicationInfo,
// esquema api://). Um replace só da URL completa com barra (o approach
// original do template) deixava os outros dois formatos intactos no
// manifesto "de produção". Substituir só o host cobre os três de uma vez.
const prodHost = urlProd ? new URL(urlProd).host : undefined;

// Reads the dev certs generated by `office-addin-dev-certs` directly instead
// of calling its getHttpsServerOptions(), which also tries to install the CA
// into the system trust store (needs an interactive sudo prompt on Linux).
// We don't need that here: the dev server is exposed to other machines via
// a cloudflared tunnel, which presents its own publicly-trusted certificate.
function getHttpsOptions() {
  const certDir = path.join(os.homedir(), ".office-addin-dev-certs");
  return {
    ca: fs.readFileSync(path.join(certDir, "ca.crt")),
    cert: fs.readFileSync(path.join(certDir, "localhost.crt")),
    key: fs.readFileSync(path.join(certDir, "localhost.key")),
  };
}

module.exports = async (env, options) => {
  const dev = options.mode === "development";

  // M5: falha a config INTEIRA de forma síncrona e alta, antes de qualquer
  // plugin rodar — um `throw` dentro do `transform` do CopyWebpackPlugin é
  // engolido silenciosamente (o build "passa" com exit 0, só que sem
  // manifest.xml no dist/, sem nenhum erro visível). Checar aqui garante que
  // faltar PROD_APP_DOMAIN derruba o build de produção de verdade.
  if (!dev && !urlProd) {
    throw new Error(
      "PROD_APP_DOMAIN não está definido — obrigatório pra gerar o manifesto de produção " +
        "(ex.: PROD_APP_DOMAIN=https://app.wing.com.br). Build de produção abortado.",
    );
  }

  const config = {
    devtool: "source-map",
    experiments: {
      asyncWebAssembly: true,
    },
    context: path.resolve(__dirname, "./"),
    entry: {
      polyfill: ["core-js/stable", "regenerator-runtime/runtime"],
      react: ["react", "react-dom"],
      taskpane: {
        import: ["./src/taskpane/index.tsx", "./src/taskpane/taskpane.html"],
        dependOn: "react",
      },
      commands: "./src/commands/commands.ts",
    },
    output: {
      filename: "[name].[contenthash].js",
      clean: true,
    },
    resolve: {
      extensions: [".ts", ".tsx", ".html", ".js"],
    },
    module: {
      rules: [
        {
          test: /\.ts$/,
          exclude: /node_modules/,
          use: {
            loader: "babel-loader",
          },
        },
        {
          test: /\.tsx?$/,
          exclude: /node_modules/,
          use: ["ts-loader"],
        },
        {
          test: /\.html$/,
          exclude: /node_modules/,
          use: "html-loader",
        },
        {
          test: /\.(png|jpg|jpeg|ttf|woff|woff2|gif|ico)$/,
          type: "asset/resource",
          generator: {
            filename: "assets/[name][ext][query]",
          },
        },
      ],
    },
    plugins: [
      new Dotenv(),
      new HtmlWebpackPlugin({
        filename: "taskpane.html",
        template: "./src/taskpane/taskpane.html",
        chunks: ["polyfill", "taskpane", "react"],
      }),
      new CopyWebpackPlugin({
        patterns: [
          {
            from: "assets/*",
            to: "assets/[name][ext][query]",
          },
          {
            from: "assets/model",
            to: "assets/model",
          },
          {
            from: "manifest*.xml",
            to: "[name]" + "[ext]",
            filter(resourcePath) {
              const filename = path.basename(resourcePath);
              // Backup manual antigo (domínio "gemini-word", já renomeado) —
              // nunca deveria ir pro build, dev ou produção.
              if (filename === "manifest copy.xml") return false;
              // M5: o manifesto do túnel de dev nunca pode ir parar no
              // artefato de produção implantado.
              if (!dev && filename === "manifest-tunnel.xml") return false;
              return true;
            },
            transform(content) {
              // prodHost é garantido aqui: o check no topo do módulo já
              // derrubou o build antes de chegar nesse ponto se faltasse.
              if (dev) {
                return content;
              }
              return content.toString().replace(new RegExp(devHost, "g"), prodHost);
            },
          },
        ],
      }),
      new HtmlWebpackPlugin({
        filename: "commands.html",
        template: "./src/commands/commands.html",
        chunks: ["polyfill", "commands"],
      }),
      new webpack.ProvidePlugin({
        Promise: ["es6-promise", "Promise"],
      }),
    ],
    devServer: {
      host: "0.0.0.0",
      hot: false,
      liveReload: false,
      client: false,
      // Proxy only in development mode (options.mode === 'development')
      ...(options.mode === "development"
        ? {
            proxy: [
              {
                context: "/api",
                target: process.env.DEV_API_TARGET || "http://127.0.0.1:3005", // backend dev (plain HTTP in dev)
                secure: false, // aceita certificado auto‑assinado
                changeOrigin: true,
              },
            ],
          }
        : {}),
      headers: {
        "Access-Control-Allow-Origin": "*",
        "Permissions-Policy": "clipboard-write=*",
      },
      allowedHosts: "all",
      server: {
        type: "https",
        options:
          env.WEBPACK_BUILD || options.https !== undefined
            ? options.https
            : await getHttpsOptions(),
      },
      port: process.env.npm_package_config_dev_server_port || 5173,
    },
  };

  return config;
};
